---

- hosts: all
  roles:
          - role: repository
            remote_user: debian
            become: true
            become_user: root
            become_method: su
            connection: ssh  
  
