---
- name : Add DotDeb Key
  apt_key:
          url: https://dotdeb.org/dotdeb.gpg
          state: present

- name: Debian Repo
  include_tasks: debian/main.yml
  when: ansible_distribution == "Debian"

- name: Ubuntu Repo
  include_tasks: ubuntu/main.yml
  when: ansible_distribution == "Ubuntu"
 
- name: Update apt packages
  apt:
          update_cache: yes

